export const ADD_SCHOOL = "ADD_SCHOOL";
export const DELETE_SCHOOL = "DELETE_SCHOOL";

export const ADD_TEACHER = "ADD_TEACHER";
export const DELETE_TEACHER="DELETE_TEACHER"

export const ADD_CLASSROOM = "ADD_CLASSROOM";
export const DELETE_CLASSROOM = "DELETE_CLASSROOM";

export const OPEN_TEACHER_FORM = "OPEN_TEACHER_FORM";
export const CLOSE_TEACHER_FORM = "CLOSE_TEACHER_FORM";

export const OPEN_SCHOOL_FORM = "OPEN_SCHOOL_FORM";
export const CLOSE_SCHOOL_FORM = "CLOSE_SCHOOL_FORM";
